'use client';

import * as React from 'react';
import { Check, Copy, KeyRound, TriangleAlert } from 'lucide-react';
import type { ManagerCredentials } from '@/lib/api/resources';
import { useI18n } from '@/components/layout/I18nProvider';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/Card';

/**
 * Shows a generated username and password once, with copy buttons.
 *
 * ## Why this is a panel that must be dismissed, not a toast
 *
 * The server stores only an Argon2 hash, so this is genuinely the only time these
 * characters exist anywhere the admin can reach. A notification that fades after
 * five seconds would, for a real fraction of academies, mean an account nobody can
 * ever sign in to — recoverable only by an admin knowing to hit "reset password",
 * which is a support ticket generated by a UI decision.
 *
 * So: it stays until acknowledged, the acknowledgement is explicit, and the warning
 * says plainly that the password will not be shown again.
 */
export function CredentialsPanel({
  credentials,
  onDismiss,
}: {
  credentials: ManagerCredentials;
  onDismiss: () => void;
}) {
  const { t } = useI18n();

  return (
    <Card className="border-success/50 bg-success/5">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <KeyRound className="text-success size-4" aria-hidden /> {t.admin.credentialsTitle}
        </CardTitle>
        <CardDescription>{t.admin.credentialsHint}</CardDescription>
      </CardHeader>
      <CardContent className="space-y-3">
        <CopyRow label={t.admin.username} value={credentials.username} />
        <CopyRow label={t.admin.password} value={credentials.password} mono />

        <p className="text-warning flex items-start gap-1.5 text-xs">
          <TriangleAlert className="mt-px size-3.5 shrink-0" aria-hidden />
          {t.admin.credentialsWarning}
        </p>

        <div className="flex flex-wrap gap-2">
          <CopyRowButton
            label={t.admin.copyBoth}
            value={`${t.admin.username}: ${credentials.username}\n${t.admin.password}: ${credentials.password}`}
          />
          <Button variant="outline" size="sm" onClick={onDismiss}>
            {t.admin.credentialsSaved}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}

function CopyRow({ label, value, mono }: { label: string; value: string; mono?: boolean }) {
  return (
    <div className="border-border bg-surface flex items-center gap-2 rounded-lg border p-2.5">
      <span className="text-muted w-20 shrink-0 text-xs uppercase">{label}</span>
      <code className={`min-w-0 flex-1 truncate text-sm ${mono ? 'font-mono tracking-wide' : ''}`}>
        {value}
      </code>
      <CopyRowButton label="" value={value} iconOnly />
    </div>
  );
}

function CopyRowButton({
  label,
  value,
  iconOnly,
}: {
  label: string;
  value: string;
  iconOnly?: boolean;
}) {
  const { t } = useI18n();
  const [copied, setCopied] = React.useState(false);

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(value);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard access can be refused (insecure origin, denied permission). The
      // text is on screen and selectable, so failing silently costs nothing —
      // whereas an error toast over a credential panel is pure alarm.
    }
  };

  return (
    <Button
      type="button"
      variant={iconOnly ? 'ghost' : 'outline'}
      size="sm"
      onClick={copy}
      aria-label={iconOnly ? t.common.copy : undefined}
    >
      {copied ? <Check aria-hidden /> : <Copy aria-hidden />}
      {!iconOnly && (copied ? t.common.copied : label)}
    </Button>
  );
}
